version: "3"
services:
  mysql:
    image: mysql:5.6.27
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: codecamp
volumes:
  mysqldata:
    driver: local
